const DEMO_TIMESTAMP = "2026-01-01T00:00:00.000Z";

const seedFoodItems = [
  {
    id: 1,
    name: "Grilled Chicken Breast",
    brand: "HealthyLife Demo",
    category: "protein",
    servingSize: "100 g",
    calories: 165,
    protein: 31,
    carbs: 0,
    fats: 3.6,
    dietTags: ["high_protein", "gluten_free"],
    allergens: []
  },
  {
    id: 2,
    name: "Brown Rice",
    brand: "HealthyLife Demo",
    category: "grain",
    servingSize: "1 cup cooked",
    calories: 216,
    protein: 5,
    carbs: 45,
    fats: 1.8,
    dietTags: ["vegan", "vegetarian"],
    allergens: []
  },
  {
    id: 3,
    name: "Greek Yogurt",
    brand: "HealthyLife Demo",
    category: "dairy",
    servingSize: "170 g",
    calories: 100,
    protein: 17,
    carbs: 6,
    fats: 0,
    dietTags: ["vegetarian", "high_protein"],
    allergens: ["milk"]
  },
  {
    id: 4,
    name: "Lentil Soup",
    brand: "HealthyLife Demo",
    category: "prepared",
    servingSize: "1 bowl",
    calories: 230,
    protein: 14,
    carbs: 36,
    fats: 4,
    dietTags: ["vegan", "vegetarian", "high_fiber"],
    allergens: []
  },
  {
    id: 5,
    name: "Almond Butter Toast",
    brand: "HealthyLife Demo",
    category: "snack",
    servingSize: "1 slice",
    calories: 260,
    protein: 9,
    carbs: 24,
    fats: 15,
    dietTags: ["vegetarian"],
    allergens: ["tree_nuts", "gluten"]
  },
  {
    id: 6,
    name: "Tavuk döner dürüm",
    brand: "HealthyLife Turkish Demo",
    category: "wrap",
    servingSize: "1 dürüm, about 385 g",
    calories: 581,
    protein: 35,
    carbs: 76.3,
    fats: 14.1,
    dietTags: ["turkish_food", "student_friendly", "doner", "dürüm", "durum", "tavuk", "high_protein"],
    allergens: ["gluten", "milk"]
  },
  {
    id: 7,
    name: "Et döner porsiyon",
    brand: "HealthyLife Turkish Demo",
    category: "prepared",
    servingSize: "1 plate, about 200 g meat",
    calories: 722,
    protein: 35.8,
    carbs: 7.6,
    fats: 61,
    dietTags: ["turkish_food", "doner", "döner", "et", "beef", "kebap", "high_protein"],
    allergens: ["milk"]
  },
  {
    id: 8,
    name: "Adana kebap",
    brand: "HealthyLife Turkish Demo",
    category: "grill",
    servingSize: "1 medium portion, about 151 g",
    calories: 361,
    protein: 21,
    carbs: 12.5,
    fats: 25.7,
    dietTags: ["turkish_food", "kebap", "kebab", "adana", "grill", "high_protein"],
    allergens: ["gluten"]
  },
  {
    id: 9,
    name: "Urfa kebap",
    brand: "HealthyLife Turkish Demo",
    category: "grill",
    servingSize: "1 medium portion, about 150 g",
    calories: 348,
    protein: 20.5,
    carbs: 9,
    fats: 25.5,
    dietTags: ["turkish_food", "kebap", "kebab", "urfa", "grill", "high_protein"],
    allergens: ["gluten"]
  },
  {
    id: 10,
    name: "İskender kebap",
    brand: "HealthyLife Turkish Demo",
    category: "prepared",
    servingSize: "1 portion, about 400 g",
    calories: 589,
    protein: 37.9,
    carbs: 71.3,
    fats: 15.8,
    dietTags: ["turkish_food", "kebap", "kebab", "iskender", "isgender", "doner", "high_protein"],
    allergens: ["gluten", "milk"]
  },
  {
    id: 11,
    name: "Lahmacun",
    brand: "HealthyLife Turkish Demo",
    category: "flatbread",
    servingSize: "1 piece",
    calories: 487,
    protein: 21.5,
    carbs: 70.9,
    fats: 12.7,
    dietTags: ["turkish_food", "lahmacun", "flatbread", "student_friendly"],
    allergens: ["gluten"]
  },
  {
    id: 12,
    name: "Menemen",
    brand: "HealthyLife Turkish Demo",
    category: "breakfast",
    servingSize: "1 serving, about 250 g",
    calories: 260,
    protein: 13,
    carbs: 12,
    fats: 18,
    dietTags: ["turkish_food", "menemen", "breakfast", "vegetarian", "student_friendly"],
    allergens: ["egg"]
  },
  {
    id: 13,
    name: "Mercimek çorbası",
    brand: "HealthyLife Turkish Demo",
    category: "soup",
    servingSize: "1 bowl, about 248 g",
    calories: 186,
    protein: 10.4,
    carbs: 26.6,
    fats: 4.6,
    dietTags: ["turkish_food", "mercimek", "lentil", "soup", "çorba", "corba", "vegetarian", "high_fiber", "student_friendly"],
    allergens: []
  },
  {
    id: 14,
    name: "Ezogelin çorbası",
    brand: "HealthyLife Turkish Demo",
    category: "soup",
    servingSize: "1 bowl, about 250 g",
    calories: 145,
    protein: 4.7,
    carbs: 14.9,
    fats: 2.9,
    dietTags: ["turkish_food", "ezogelin", "lentil", "bulgur", "soup", "çorba", "corba", "vegetarian", "student_friendly"],
    allergens: ["gluten", "milk"]
  },
  {
    id: 15,
    name: "Bulgur pilavı",
    brand: "HealthyLife Turkish Demo",
    category: "grain",
    servingSize: "1 cup cooked, about 182 g",
    calories: 246,
    protein: 5.6,
    carbs: 41.8,
    fats: 6.5,
    dietTags: ["turkish_food", "bulgur", "pilav", "grain", "vegetarian", "student_friendly"],
    allergens: ["gluten"]
  },
  {
    id: 16,
    name: "Ayran",
    brand: "HealthyLife Turkish Demo",
    category: "drink",
    servingSize: "1 cup, about 245 ml",
    calories: 86,
    protein: 4.8,
    carbs: 6.6,
    fats: 4.5,
    dietTags: ["turkish_food", "ayran", "drink", "vegetarian", "student_friendly"],
    allergens: ["milk"]
  },
  {
    id: 17,
    name: "Simit",
    brand: "HealthyLife Turkish Demo",
    category: "bakery",
    servingSize: "1 normal simit",
    calories: 270,
    protein: 10.5,
    carbs: 53,
    fats: 1.7,
    dietTags: ["turkish_food", "simit", "bakery", "breakfast", "vegetarian", "student_friendly"],
    allergens: ["gluten", "sesame"]
  },
  {
    id: 18,
    name: "Kıymalı pide",
    brand: "HealthyLife Turkish Demo",
    category: "flatbread",
    servingSize: "1 medium pide, about 250 g",
    calories: 533,
    protein: 20.3,
    carbs: 80.8,
    fats: 13,
    dietTags: ["turkish_food", "pide", "kiymali", "kıymalı", "flatbread", "student_friendly"],
    allergens: ["gluten"]
  },
  {
    id: 19,
    name: "Tavuk şiş",
    brand: "HealthyLife Turkish Demo",
    category: "grill",
    servingSize: "1 medium portion, about 165 g",
    calories: 208,
    protein: 30.5,
    carbs: 3.4,
    fats: 7.9,
    dietTags: ["turkish_food", "tavuk", "sis", "şiş", "grill", "high_protein"],
    allergens: []
  },
  {
    id: 20,
    name: "Köfte",
    brand: "HealthyLife Turkish Demo",
    category: "grill",
    servingSize: "100 g",
    calories: 204,
    protein: 16.2,
    carbs: 6.5,
    fats: 12.1,
    dietTags: ["turkish_food", "köfte", "kofte", "meatball", "grill", "high_protein", "student_friendly"],
    allergens: ["gluten", "egg"]
  },
  {
    id: 21,
    name: "Protein milk",
    brand: "HealthyLife Demo",
    category: "drink",
    servingSize: "250 ml",
    calories: 160,
    protein: 25,
    carbs: 12,
    fats: 2,
    dietTags: ["high_protein", "student_friendly", "drink"],
    allergens: ["milk"]
  },
  {
    id: 22,
    name: "Boiled eggs",
    brand: "HealthyLife Demo",
    category: "breakfast",
    servingSize: "2 eggs, about 100 g",
    calories: 155,
    protein: 13,
    carbs: 1.1,
    fats: 10.6,
    dietTags: ["high_protein", "breakfast", "vegetarian", "budget"],
    allergens: ["egg"]
  },
  {
    id: 23,
    name: "Tuna sandwich",
    brand: "HealthyLife Demo",
    category: "sandwich",
    servingSize: "1 sandwich, about 220 g",
    calories: 420,
    protein: 34,
    carbs: 42,
    fats: 12,
    dietTags: ["high_protein", "student_friendly", "lunch"],
    allergens: ["fish", "gluten"]
  },
  {
    id: 24,
    name: "Chicken rice bowl",
    brand: "HealthyLife Demo",
    category: "prepared",
    servingSize: "1 bowl, about 400 g",
    calories: 620,
    protein: 42,
    carbs: 58,
    fats: 18,
    dietTags: ["high_protein", "meal", "student_friendly"],
    allergens: []
  },
  {
    id: 25,
    name: "Protein oatmeal",
    brand: "HealthyLife Demo",
    category: "breakfast",
    servingSize: "1 bowl, about 300 g",
    calories: 430,
    protein: 32,
    carbs: 55,
    fats: 9,
    dietTags: ["high_protein", "breakfast", "fiber", "student_friendly"],
    allergens: ["gluten", "milk"]
  },
  {
    id: 26,
    name: "Banana",
    brand: "HealthyLife Demo",
    category: "fruit",
    servingSize: "1 medium banana, about 118 g",
    calories: 105,
    protein: 1.3,
    carbs: 27,
    fats: 0.4,
    dietTags: ["snack", "vegan", "budget", "carb_source"],
    allergens: []
  },
  {
    id: 27,
    name: "Protein bar",
    brand: "HealthyLife Demo",
    category: "snack",
    servingSize: "1 bar, about 60 g",
    calories: 220,
    protein: 20,
    carbs: 22,
    fats: 7,
    dietTags: ["high_protein", "snack", "student_friendly"],
    allergens: ["milk", "tree_nuts"]
  },
  {
    id: 28,
    name: "Peanut butter toast",
    brand: "HealthyLife Demo",
    category: "snack",
    servingSize: "1 toast, about 90 g",
    calories: 330,
    protein: 13,
    carbs: 31,
    fats: 18,
    dietTags: ["snack", "budget", "vegetarian"],
    allergens: ["peanut", "gluten"]
  },
  {
    id: 29,
    name: "Cacık",
    brand: "HealthyLife Turkish Demo",
    category: "side",
    servingSize: "1 bowl, about 200 g",
    calories: 110,
    protein: 6,
    carbs: 9,
    fats: 5,
    dietTags: ["turkish_food", "cacik", "side", "vegetarian"],
    allergens: ["milk"]
  },
  {
    id: 30,
    name: "Zeytinyağlı salata",
    brand: "HealthyLife Turkish Demo",
    category: "salad",
    servingSize: "1 bowl, about 250 g",
    calories: 190,
    protein: 4,
    carbs: 14,
    fats: 13,
    dietTags: ["turkish_food", "salad", "vegetarian", "low_calorie"],
    allergens: []
  },
  {
    id: 31,
    name: "Nohut yemeği",
    brand: "HealthyLife Turkish Demo",
    category: "prepared",
    servingSize: "1 plate, about 250 g",
    calories: 360,
    protein: 16,
    carbs: 52,
    fats: 10,
    dietTags: ["turkish_food", "chickpea", "nohut", "vegetarian", "budget"],
    allergens: []
  },
  {
    id: 32,
    name: "Tavuklu makarna",
    brand: "HealthyLife Turkish Demo",
    category: "prepared",
    servingSize: "1 plate, about 350 g",
    calories: 590,
    protein: 38,
    carbs: 72,
    fats: 14,
    dietTags: ["turkish_food", "pasta", "chicken", "high_protein", "student_friendly"],
    allergens: ["gluten"]
  }
];

function getSeedFoodItems() {
  return seedFoodItems.map((item) => ({
    source: "demo_estimate",
    createdAt: DEMO_TIMESTAMP,
    updatedAt: DEMO_TIMESTAMP,
    ...item
  }));
}

module.exports = {
  getSeedFoodItems
};
